/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gsmtap_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b434cfedf81d87ff8e23e8fbf8ebdf14)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gmr1/gsmtap_sink.h>
// pydoc.h is automatically generated in the build directory
#include <gsmtap_sink_pydoc.h>

void bind_gsmtap_sink(py::module& m)
{

    using gsmtap_sink = ::gr::gmr1::gsmtap_sink;


    py::class_<gsmtap_sink, gr::block, gr::basic_block, std::shared_ptr<gsmtap_sink>>(
        m, "gsmtap_sink", D(gsmtap_sink))

        .def(py::init(&gsmtap_sink::make),
             py::arg("host"),
             py::arg("port"),
             D(gsmtap_sink, make))


        .def("host", &gsmtap_sink::host, D(gsmtap_sink, host))


        .def("port", &gsmtap_sink::port, D(gsmtap_sink, port))

        ;
}
