/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-gmr1
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_GMR1_API_H
#define INCLUDED_GMR1_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_gmr1_EXPORTS
#define GMR1_API __GR_ATTR_EXPORT
#else
#define GMR1_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_GMR1_API_H */
